export const METAMASK_DOWLOAD = 'https://metamask.io/download';

export const SECOND_NUMBER = 60;

export const PERCENTAGE_NUMBER = 100;
export const PERCENTAGE_SUFFIX = '%';

export const TOKEN_SUPPORT = {
  symbol: 'USDC',
  icon: 'https://s3.coinmarketcap.com/static-gravity/image/5a8229787b5e4c809b5914eef709b59a.png',
  value: 'usd',
};

export const LENGTH_CONSTANTS = {
  MAX_LENGTH_INPUT: 256,
  DEFAULT_PAGE_SIZE: 10,
  DEFAULT_PAGE_SIZE_OPTIONS: ['10', '20', '50'],
  DEFAULT_PAGE: 1,
  DEFAULT_TOTAL: 0,
  MAX_COLUMNS: 9,
  MAX_TAB_COLUMNS: 7,
  MAX_LIMIT: 999999999,
  MIN_VALUE: 1e-8,
  MIN_SIZE_IMAGE: 300,
  MIN_VALUE_SELECT: 3,
  MAX_LENGTH_EVENT_NAME: 128,
  MAX_LENGTH_REQUIRE_BALANCE: 4,
  MAX_LENGTH_ALLOCATED_REWARD_INTEGER: 12,
  MAX_LENGTH_ALLOCATED_REWARD_DECIMAL: 2,
};

export const TIME_CONSTANTS = {
  DEBOUNCE_SEARCH_TIME: 500,
  EXPIRE_ACCESSED_TIME: 5,
  DEBOUNCE_SEARCH_LIST: 1000,
};

export const EMPTY_TEXT = '--';
export const MAX_CODE_LENGTH = 10;
