export const FUNCTION = 'function';

export const PROPERTY = 'property';

export const ARRAY = 'array';

export const OBJECT = 'object';

export const STRING = 'string';

export const NUMBER = 'number';

export const UNDEFINED = 'undefined';

export const TYPE_TYPOGRAPHY = {
  TEXT_SUFFIX: 'TEXT_SUFFIX',
  TEXT_ELLIPSIS: 'TEXT_ELLIPSIS',
  TEXT_EXPAND: 'TEXT_EXPAND',
};

export const TYPE_TABLE = {
  TABLE: 'TABLE',
  EDIT_TABLE: 'EDIT_TABLE',
  SORT_TABLE: 'SORT_TABLE',
  TABLE_LIST: 'TABLE_LIST',
};

export const TYPE_INPUT = {
  TEXT: 'TEXT',
  TEXTAREA: 'TEXTAREA',
  DATE: 'DATE',
  PASSWORD: 'PASSWORD',
  SELECT: 'SELECT',
  CHECKBOX: 'CHECKBOX',
  CHECKBOXGROUP: 'CHECKBOXGROUP',
  NUMBER: 'NUMBER',
  SEARCH: 'SEARCH',
  SELECT_INFINITY_SCROLL: 'SELECT_INFINITY_SCROLL',
  SWITCH: 'SWITCH',
  RADIO: 'RADIO',
  AUTOCOMPLETE: 'AUTOCOMPLETE',
  RANGE: 'RANGE',
  SEARCH_DEBOUNCE: 'SEARCH_DEBOUNCE',
};
