import { ReactNode } from 'react';
export type InputDesignProps = {
  customComponent?: any;
  type?: string;
  name: string;
  typeInput?: string | null;
  prefix?: symbol | ReactNode | string;
  placeholder?: string | any;
  label?: string | number | ReactNode;
  content?: string | number | ReactNode;
  maxLength?: number;
  onChange?: any;
  showSearch?: boolean;
  errorClassName?: string;
  required?: boolean;
  onSearch?: any;
  onKeyDown?: any;
  values?: any;
  unit?: string;
  errorField?: string;
  description?: string | ReactNode;
  disabled?: boolean;
  validate?: any;
  textTooltip?: string;
  labelTootip?: string;
  labelClassName?: string;
  appendInput?: ReactNode;
  options?: {
    value: string | number;
    name: string | number;
    key?: string | number;
  }[];
  className?: string;
  children?: ReactNode;
  [key: string]: any;
};
